name: Build
on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: ">=1.19"
                  check-latest: true
                  cache: true
            - name: Build
              run: go build -v ./...
            - name: Test
              run: go test -v ./...
            - name: Run coverage
              run: go test -race -coverprofile=coverage.out -covermode=atomic
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v3
              with:
                  token: 094a0017-2141-4c42-aa24-d89cf7b0a87a
    build-1-18:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.18
                  check-latest: true
                  cache: true
            - name: Build
              run: go build -v ./...
            - name: Test
              run: go test -v ./...
    build-1-19:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.19
                  check-latest: true
                  cache: true
            - name: Build
              run: go build -v ./...

            - name: Test
              run: go test -v ./...
